services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  tweed:
    build: .
    container_name: tweed-app-test
    environment:
      - NODE_ENV=test
      - PORT=3001
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - STANDARD_TIER_RATE_LIMIT=5
      - HIGH_TIER_RATE_LIMIT=30
      - SLIDING_WINDOW_TIME_IN_SEC=10
    ports:
      - "3001:3000"
    depends_on:
      - redis
    command: ["sh", "-c", "npm test"]