version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rate-limiter:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
